Resources:
  WelcomeHandlerServiceRoleA03808BE:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: Lambda-Stack/WelcomeHandler/ServiceRole/Resource
  WelcomeHandlerBD29C4C1:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-us-west-2
        S3Key: a012fb89eb4db26a481e85c7bd2143af151a9ef212c5fb6d1c16f6e62cb70bac.zip
      Handler: welcome.handler
      Role:
        Fn::GetAtt:
          - WelcomeHandlerServiceRoleA03808BE
          - Arn
      Runtime: python3.12
    DependsOn:
      - WelcomeHandlerServiceRoleA03808BE
    Metadata:
      aws:cdk:path: Lambda-Stack/WelcomeHandler/Resource
      aws:asset:path: asset.a012fb89eb4db26a481e85c7bd2143af151a9ef212c5fb6d1c16f6e62cb70bac
      aws:asset:is-bundled: false
      aws:asset:property: Code
  EndpointEEF1FD8F:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Endpoint
    Metadata:
      aws:cdk:path: Lambda-Stack/Endpoint/Resource
  EndpointDeployment318525DAdf6af99701754413ae5d9c96fd7a9d88:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Automatically created by the RestApi construct
      RestApiId:
        Ref: EndpointEEF1FD8F
    DependsOn:
      - EndpointproxyANYC09721C5
      - Endpointproxy39E2174E
      - EndpointANY485C938B
    Metadata:
      aws:cdk:path: Lambda-Stack/Endpoint/Deployment/Resource
  EndpointDeploymentStageprodB78BEEA0:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: EndpointDeployment318525DAdf6af99701754413ae5d9c96fd7a9d88
      RestApiId:
        Ref: EndpointEEF1FD8F
      StageName: prod
    Metadata:
      aws:cdk:path: Lambda-Stack/Endpoint/DeploymentStage.prod/Resource
  Endpointproxy39E2174E:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - EndpointEEF1FD8F
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: Lambda-Stack/Endpoint/Default/{proxy+}/Resource
  EndpointproxyANYApiPermissionLambdaStackEndpoint1B623971ANYproxyFD85AFB4:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - WelcomeHandlerBD29C4C1
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-west-2:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /
            - Ref: EndpointDeploymentStageprodB78BEEA0
            - /*/*
    Metadata:
      aws:cdk:path: Lambda-Stack/Endpoint/Default/{proxy+}/ANY/ApiPermission.LambdaStackEndpoint1B623971.ANY..{proxy+}
  EndpointproxyANYApiPermissionTestLambdaStackEndpoint1B623971ANYproxy92CEEC5F:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - WelcomeHandlerBD29C4C1
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-west-2:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: Lambda-Stack/Endpoint/Default/{proxy+}/ANY/ApiPermission.Test.LambdaStackEndpoint1B623971.ANY..{proxy+}
  EndpointproxyANYC09721C5:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - WelcomeHandlerBD29C4C1
                  - Arn
              - /invocations
      ResourceId:
        Ref: Endpointproxy39E2174E
      RestApiId:
        Ref: EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: Lambda-Stack/Endpoint/Default/{proxy+}/ANY/Resource
  EndpointANYApiPermissionLambdaStackEndpoint1B623971ANY60A9DD33:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - WelcomeHandlerBD29C4C1
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-west-2:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /
            - Ref: EndpointDeploymentStageprodB78BEEA0
            - /*/
    Metadata:
      aws:cdk:path: Lambda-Stack/Endpoint/Default/ANY/ApiPermission.LambdaStackEndpoint1B623971.ANY..
  EndpointANYApiPermissionTestLambdaStackEndpoint1B623971ANY2EB70ACE:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - WelcomeHandlerBD29C4C1
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-west-2:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: Lambda-Stack/Endpoint/Default/ANY/ApiPermission.Test.LambdaStackEndpoint1B623971.ANY..
  EndpointANY485C938B:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - WelcomeHandlerBD29C4C1
                  - Arn
              - /invocations
      ResourceId:
        Fn::GetAtt:
          - EndpointEEF1FD8F
          - RootResourceId
      RestApiId:
        Ref: EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: Lambda-Stack/Endpoint/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02OQW6DQAxFz5L94CohUtdJq65aFZEDRA64xIWZQdgjitDcvRpIK1b/+dv+9gH2x2fIdzhKVtVt1vEN5oti1Roc5Tp3aG81wvwWXKXsnXn5clsuaLAswt5Fw2hhLn1HqZE0GsmvKEIqcEpiJIdzqFrSMwoZ7LlBpREnmN+XQyWJnnpeAh74Sn3nJ0tOk7upLorNcmqFksSHoaIluRj8z/TnPNJW/iC9+zpZK8X4v2mWH1MauyZNfAbtg27XoykmvXv3lMP+AMfdtzBnQ3DKlqBc9Rc5TbU6UwEAAA==
    Metadata:
      aws:cdk:path: Lambda-Stack/CDKMetadata/Default
Outputs:
  Endpoint8024A810:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: EndpointEEF1FD8F
          - .execute-api.us-west-2.
          - Ref: AWS::URLSuffix
          - /
          - Ref: EndpointDeploymentStageprodB78BEEA0
          - /
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

